- name: roles
  hosts: all
  become: true
  roles:
    - role: install_docker
    - role: create_network
    - role: launch_database
      vars:
        database_env: "{{ database_env }}"
    - role: launch_app
      vars:
        database_env: "{{ database_env }}"
    - role: launch_proxy
