---
# tasks file for roles/launch_database
- name: Run postgresql
  docker_container:
    name: postgresql
    image: jorisgarcia/jga-postgresql:1.0
    networks:
      - name: app-network
    env:
      POSTGRES_DB: "{{ database_env.POSTGRES_DB }}"
      POSTGRES_USER: "{{ database_env.POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ database_env.POSTGRES_PASSWORD }}"