---
# tasks file for roles/launch_database
- name: Run postgresql
  docker_container:
    name: postgresql
    image: "{{ DOCKER_NAME }}/tp-devops-postgresql:latest"
    networks:
      - name: "{{ DOCKER_NETWORK }}"
    env:
      POSTGRES_DB: "{{ DATABASE_DB }}"
      POSTGRES_USER: "{{ DATABASE_USER }}"
      POSTGRES_PASSWORD: "{{ DATABASE_PASSWORD }}"