---
# tasks file for roles/launch_database
- name: Run postgresql
  docker_container:
    name: postgresql
    image: jorisgarcia/jga-postgresql:1.0
    networks:
      - name: app-network
    env:
      POSTGRES_DB: "{{ POSTGRES_DB }}"
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"