---
# tasks file for roles/launch_app
- name: Run Api
  docker_container:
    name: api
    image: "{{ DOCKER_NAME }}/tp-devops-serveur:latest"
    networks:
      - name: {{ DOCKER_NETWORK }}
      - name: app-proxy
    env:
      POSTGRES_DB: "{{ DATABASE_DB }}"
      POSTGRES_USER: "{{ DATABASE_USER }}"
      POSTGRES_PASSWORD: "{{ DATABASE_PASSWORD }}"