---
# tasks file for roles/launch_proxy
- name: Run HTTPD
  docker_container:
    name: httpd
    image: "{{ DOCKER_NAME }}/tp-devops-serveur:latest"
    ports:
      - "80:80"
    networks:
      - name: "{{ DOCKER_NETWORK }}"
