name: deploy

on:
  workflow_run:
    workflows: [buildpush]
    types: 
      - completed
    branches: 
      - main

jobs:
  deploy:
    # Plateforme d'exécution
    runs-on: ubuntu-22.04

    # Lancer les etapes si le worflow précédent n'a pas échoué 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.5.0

    # Etape pour la connexion à DockerHub
    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Ansible Docker image
      uses: docker/build-push-action@v3
      with:
        # Chemin relatif où se trouve le code source avec le Dockerfile
        context: ./TP3/ansible
        # Crée un tag pour l'image Docker
        tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-ansible:latest
        # Publie si le workflow a été déclenché par un push sur la branche main 
        push: ${{ github.ref == 'refs/heads/main' }}

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Ansible playbook
      run: |
        docker run --rm \
        -v $SSH_AUTH_SOCK:/ssh-auth-sock \
        -e SSH_AUTH_SOCK=/ssh-auth-sock \
        -w /ansible \
        -e ANSIBLE_VAULT_PASSWORD=${{ secrets.ANSIBLE_VAULT_PASSWORD }} \
        ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-ansible:latest \
        ansible-playbook -i inventories/setup.yml roles.yml

    - name: Notify deployment success
      run: echo "Deployment successful!"
